### ISSUE TITLE
Change org name to reflect our new name

### ISSUE THREAD

**Issue by cfhammill** [LKS-CHART/blog#37]
It would be nice if we changed our organization name on github to DSAA to reflect our current organization name elsewhere.

Option one: @dsaa would you consider releasing your github account so that we can use that name for our organization?
Option two: we could try UHT-DSAA?

**Comment by cfhammill** [comment]
edit @dsaa if you would be willing please reach out to us here or at my email cfhammill@gmail.com

**Comment by cfhammill** [comment]
@chloepouprom @derekbeaton @Michaeliay What do you all think of switching the org name to UHT-DSAA? Downside I can see if potentially breaking git backed deployments if we're not careful

**Comment by chloepouprom** [comment]
I like that idea!

I think most of the Git-backed deployments have been moved to Gitlab or can easily be re-deployed manually.

Any sites on the lks-chart.github.io link would break:
- https://lks-chart.github.io/blog/
- https://lks-chart.github.io/CHARTextract-docs/
- https://lks-chart.github.io/gim-data-dictionary/
- https://lks-chart.github.io/chartdb/
Of the links above, only the blog is really used, so I don't think it would be an issue.
