### ISSUE TITLE
Review post simulation blog post

### ISSUE THREAD

**Issue by neilmistry** [LKS-CHART/blog#41]
Review at a higher level please to see if this is the correct content.  I am thinking that we may have more then one blog post regarding Simulations (DES).  First blog post is more getting familiar with DES, software options, applications in healthcare and brief overview of one application.  The old post is still there as well, which can be edited or removed.  Post located here: 

https://github.com/LKS-CHART/blog/tree/post_simulation/_posts/2023-03-17-introduction-to-discrete-event-simulations-in-healthcare

**Comment by chloepouprom** [comment]
I created PR #42 so that it's easier to track comments

**Comment by cfhammill** [comment]
The post branch was merged. Closing, reopen if still relevant
